/**
 * Tests for the propolis Hamming ECC encoder.
 * Reference values were generated by compiling and running Pierre Abbat's
 * C++ implementation directly (vendor/propolis/).
 */
import { describe, it, expect } from 'vitest';

// Re-export internals under test — we expose them from encodeECC.ts
import {
  _test_databits,
  _test_arrangeHamming,
  _test_crissCrossFactor,
  _test_appendCheckLetters,
  _test_hammingEncode,
  _test_encodeByte,
  _test_findSize,
  _test_whiten,
  encodeTextECC,
} from './encodeECC.js';

// ── databits ─────────────────────────────────────────────────────────────────

describe('databits', () => {
  it('returns correct data capacity for Hamming codeword sizes', () => {
    expect(_test_databits(3)).toBe(1);
    expect(_test_databits(6)).toBe(3);
    expect(_test_databits(7)).toBe(4);
    expect(_test_databits(10)).toBe(6);
    expect(_test_databits(12)).toBe(8);
    expect(_test_databits(13)).toBe(9);
    expect(_test_databits(21)).toBe(16);
    expect(_test_databits(31)).toBe(26);
  });
});

// ── arrangeHamming ────────────────────────────────────────────────────────────

describe('arrangeHamming', () => {
  // Reference: C++ comment "31: 31 (26); 21,10 (22); 13,12,6 (20); 7,7,7,7,3 (17)"
  it('returns single block for nblocks=1', () => {
    expect(_test_arrangeHamming(31, 1)).toEqual([31]);
  });
  it('returns two blocks for nblocks=2', () => {
    expect(_test_arrangeHamming(31, 2)).toEqual([21, 10]);
  });
  it('returns three blocks for nblocks=3', () => {
    expect(_test_arrangeHamming(31, 3)).toEqual([13, 12, 6]);
  });
  it('returns four equal-ish blocks for nblocks=4', () => {
    // databits([13,6,6,6])=18, which is NOT >18, so nBlocks=3 wins in findSize
    expect(_test_arrangeHamming(31, 4)).toEqual([13, 6, 6, 6]);
  });
  it('returns five blocks for nblocks=5', () => {
    expect(_test_arrangeHamming(31, 5)).toEqual([7, 7, 7, 7, 3]);
  });
  it('matches C++ for size-4 symbol (55 letters, 4 blocks)', () => {
    expect(_test_arrangeHamming(55, 4)).toEqual([14, 14, 14, 13]);
  });
});

// ── crissCrossFactor ──────────────────────────────────────────────────────────

describe('crissCrossFactor', () => {
  // Reference: C++ arrange.cpp comment "n=55 (size 4 symbol), returns (16,8)"
  it('returns [16, 8] for n=55', () => {
    expect(_test_crissCrossFactor(55)).toEqual([16, 8]);
  });
  // Reference: C++ runtime output for "hello world" size-3 symbol
  it('returns [2, 5] for n=31', () => {
    expect(_test_crissCrossFactor(31)).toEqual([2, 5]);
  });
});

// ── whiten (round-trip sanity) ────────────────────────────────────────────────

describe('whiten', () => {
  it('produces different output from input', () => {
    // whiten should change most letters
    let diffs = 0;
    for (let i = 0; i < 31; i++) {
      if (_test_whiten(0x40 | i, 0) !== (0x40 | i)) diffs++;
    }
    expect(diffs).toBeGreaterThan(20);
  });
});

// ── encodeByte ────────────────────────────────────────────────────────────────

describe('encodeByte (mode-8 byte packing)', () => {
  // Reference: C++ encodebyte("hello world") output
  it('packs "hello world" into 18 five-bit letters', () => {
    const result = _test_encodeByte('hello world');
    expect(result.length).toBe(18);
    // Check first few codes (0x40-based)
    expect(result[0]).toBe(0x4D); // 'M'
    expect(result[1]).toBe(0x41); // 'A'
    expect(result[2]).toBe(0x52); // 'R'
    expect(result[3]).toBe(0x56); // 'V'
  });
  it('correctly packs "A" (0x41) into two letters', () => {
    // 0x41 = 0b01000001. bits=0, buf=0.
    // byte=0x41=65: buf=65, bits=8.
    // bits>=5: bits=3, push 0x40|(65>>3)&31 = 0x40|8 = 0x48.
    // bits=3<5: done with byte. remaining 3 bits = 65&7 = 1 = 0b001.
    // bits>0: push 0x40|(1<<(5-3))&31 = 0x40|(1<<2) = 0x40|4 = 0x44.
    const result = _test_encodeByte('A');
    expect(result).toEqual([0x48, 0x44]);
  });
});

// ── appendCheckLetters ────────────────────────────────────────────────────────

describe('appendCheckLetters', () => {
  // Reference: C++ test harness output for a simple string
  it('appends 2 check letters to "MNSEK" → "MNSEKFU"', () => {
    // Input is raw char codes 0x40-0x5F
    const input = 'MNSEK'.split('').map(c => c.charCodeAt(0));
    const result = _test_appendCheckLetters(input, 7);
    expect(result.length).toBe(7);
    expect(result[5]).toBe(0x46); // 'F'
    expect(result[6]).toBe(0x55); // 'U'
  });
  // Reference: C++ appendCheckLetters on encodebyte("hello world") to nDataCheck=20
  it('appends 2 check letters to the hello-world encoding', () => {
    const helloBytes = _test_encodeByte('hello world');
    const result = _test_appendCheckLetters(helloBytes, 20);
    expect(result.length).toBe(20);
    // C++ output: MARVX[CODA[V^\SLLPWZ
    expect(result[18]).toBe(0x57); // 'W'
    expect(result[19]).toBe(0x5A); // 'Z'
  });
});

// ── hammingEncode ─────────────────────────────────────────────────────────────

describe('hammingEncode', () => {
  // Reference: C++ Hamming::push_back([4D,4E,52]) → [03,1F,4D,1C,4E,52]
  it('encodes [4D,4E,52] correctly', () => {
    const result = _test_hammingEncode([0x4D, 0x4E, 0x52]);
    expect(result).toEqual([0x03, 0x1F, 0x4D, 0x1C, 0x4E, 0x52]);
  });
  it('parity positions are at powers of 2 minus 1 (0-indexed)', () => {
    // Positions 0,1,3 (1-indexed: 1,2,4) are parity
    const result = _test_hammingEncode([0x4D, 0x4E, 0x52]);
    expect(result.length).toBe(6);
    // Parity positions: 0,1,3 → low values (XOR results, not 0x40-based)
    expect(result[0]).toBeLessThan(0x40); // parity
    expect(result[1]).toBeLessThan(0x40); // parity
    expect(result[3]).toBeLessThan(0x40); // parity
    // Data positions: 2,4,5 → 0x40-based
    expect(result[2]).toBe(0x4D);
    expect(result[4]).toBe(0x4E);
    expect(result[5]).toBe(0x52);
  });
});

// ── findSize ──────────────────────────────────────────────────────────────────

describe('findSize', () => {
  // Reference: C++ findSize(18) → size=3, nLetters=31, nDataCheck=20, nBlocks=3
  it('finds correct size for "hello world" (18 data letters)', () => {
    const result = _test_findSize(18);
    expect(result).not.toBeNull();
    expect(result!.size).toBe(3);
    expect(result!.nLetters).toBe(31);
    expect(result!.nDataCheck).toBe(20);
    expect(result!.nBlocks).toBe(3);
    expect(result!.hammingSizes).toEqual([13, 12, 6]);
  });
});

// ── full encoder ──────────────────────────────────────────────────────────────

describe('encodeTextECC', () => {
  it('encodes "hello world" as radius-3 symbol with 31 data slots', () => {
    const result = encodeTextECC('hello world');
    expect(result.radius).toBe(3);
    expect(result.dataSlots).toBe(31);
    expect(result.bytesEncoded).toBe(11);
  });

  it('matches C++ letter values for "hello" size-2 ASCII encoding', () => {
    // Reference inferred from C++ --text hello --size 2 --format hmap.
    const expected = [3, 26, 26, 20, 4, 20, 10, 0, 24, 5, 13, 7, 15, 14, 7, 1, 1, 18, 1];
    const result = encodeTextECC('hello');

    // Find the data letters (non-corner positions) in HVec order
    // Corners are at norm == size^2 = 4
    const dataLetters = result.letters.filter(l => {
      const { x, y } = l.center;
      const norm = x * x + y * y - x * y;
      return norm <= 4; // exclude the outer border ring
    });

    const actual = dataLetters.map(l => l.letterIndex);
    expect(actual).toEqual(expected);
  });

  it('produces different output for different inputs', () => {
    const r1 = encodeTextECC('hello world');
    const r2 = encodeTextECC('propolis');
    // They may have different radii, but even same-radius ones should differ
    const d1 = r1.letters.map(l => l.letterIndex).join(',');
    const d2 = r2.letters.map(l => l.letterIndex).join(',');
    expect(d1).not.toBe(d2);
  });

  it('encodes "propolis" without throwing', () => {
    expect(() => encodeTextECC('propolis')).not.toThrow();
  });
});
